### ISSUE TITLE
Should all classifications share a single Foundation or should each classification have their own foundation and just harmonize those entities that they share?

### ISSUE THREAD

**Issue by samsontu** [who-fic/harmonized-cm#9]
Huib says: 
I also think that there is a complication in the way we are trying to ‘build’ a foundation, starting from the ICD-11 way of thinking and modeling, and try to fit in the ICF and ICHI. The ‘ontologies’ of ICD, ICF and ICHI are completely different, because they represent different concepts. The can share the same kinds of ‘terminologies’, like anatomical entities from the FMA, or functioning-like terms form SUMO, but in fact the concepts representing the ‘things’ in each separate classification need to be consistent with the definitions of ICHI, ICF and ICD.
So I think that each classification should have its own ‘foundation’, in which ‘shared terminologies’ are identified and linked. This is what could be called the ‘shared foundation’ and would contribute to the harmonization of all classifications. Only ‘things’ which are exactly the same can be shared, but can play a different ‘role’ or can be used in the relation-types for each defining ‘ontolgy’.

**Comment by samsontu** [comment]
I believe that we should aim for a shared Foundation instead of having a foundation for each classification because (1) ICD and ICHI need to reference ICF codes, (2) we want to explore how the classifications may be used jointly, (3) we may have linearizations (derived classifications) that cut across traditional classification boundaries (e.g., primary care classification that includes intervention and disease concepts.

**Comment by crsykes** [comment]
Apologies for delayed response, I am on the road. I agree with Samson.
I thought that the idea is for a shared foundation with common concepts described for use in any of the reference classifications and those elements that are discreet for each classification modelled in such a way that they can be picked up to create the ICD, ICHI and ICF, but are also available for derived classifications and possibly independently as classifications themselves for incorporation in data collections in new ways. 
It seems to me that the uniqueness of each classification is in the way it brings the concepts together. 
I believe the intent was to bring the ICF into the information model in such a way that some of the classification érrors or difficulties that have been experienced in update process will be addressed, which might mean some changes to the ICF as it is currently are required.

**Comment by samsontu** [comment]
In the current (May 2020) WHO strategy to import ICF and ICHI into the ICD Foundation and use the same iCAT for editing, the issue is moot.
